name: Escribe tu nombre

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      genero: 
        type: choice
        description: Selecciona tu género
        options: 
        - Masculino
        - Femenino
      edad:
        type: string
        description: Ingresa tu edad
        default: "18"
        required: false
      nombre:
        type: string
        description: Nombre
        required: true
      apellidos:
        type: string
        description: Appellidos
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    on: 

    steps:
    - name: Imprimir genero
      run: echo ${{ inputs.genero }}
    - name: Imprimir edad
      run: echo ${{ inputs.edad }}
    - name: Imprimir nombre
      run: echo ${{ inputs.nombre }}
    - name: Imprimir apellidos
      run: echo ${{ inputs.apellidos }}
